name: Auto Package

on:
  push:
    branches:
    - main
    paths:
    - assets/**
    - pack.mcmeta
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  Packer:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'chore(main): 發佈') == false

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Auto Version Change
        id: version
        run: |
          echo "翻譯包版本：${GITHUB_SHA::7}" >> $GITHUB_STEP_SUMMARY
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          sed -i 's/GitVersion/git '${GITHUB_SHA::7}'/1' pack.mcmeta

      #    echo "Override Create..."
      #    PATH_Create=assets/create/lang
      #    mkdir -p $PATH_Create
      #    wget https://raw.githubusercontent.com/Creators-of-Create/Create/mc1.18/dev/src/main/resources/assets/create/lang/zh_tw.json -P $PATH_Create

      - name: Override mods
        run: sh .github/scripts/override_mods.sh

      - name: Make ModsTranslationPack (1.19.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/encyclopedia/zh_tw/language.lang
            assets/tconstruct/book/mighty_smelting/zh_tw/language.lang
            assets/tconstruct/book/fantastic_foundry/zh_tw/language.lang
            assets/tconstruct/book/materials_and_you/zh_tw/language.lang
            assets/tconstruct/book/tinkers_gadgetry/zh_tw/language.lang
            assets/tconstruct/book/puny_smelting/zh_tw/language.lang
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.19.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.19.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.19.x.zip

      - name: Change pack format to 1.18.x
        run: |
          sed -i 's/9/8/1' pack.mcmeta

      - name: Make ModsTranslationPack (1.18.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/encyclopedia/zh_tw/language.lang
            assets/tconstruct/book/mighty_smelting/zh_tw/language.lang
            assets/tconstruct/book/fantastic_foundry/zh_tw/language.lang
            assets/tconstruct/book/materials_and_you/zh_tw/language.lang
            assets/tconstruct/book/tinkers_gadgetry/zh_tw/language.lang
            assets/tconstruct/book/puny_smelting/zh_tw/language.lang
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.18.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.18.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.18.x.zip

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Make Checksum
        id: checksum
        run: |
          echo "sum-01=$(sha256sum ModsTranslationPack-1.19.x.zip)" >> $GITHUB_OUTPUT
          echo "sum-02=$(sha256sum ModsTranslationPack-1.18.x.zip)" >> $GITHUB_OUTPUT

      - name: Make Current Time
        id: current_time
        run: |
          echo "time=$(TZ='Asia/Taipei' date +'最後更新：%Y 年 %m 月 %d 日 %H 點 %M 分')" >> $GITHUB_OUTPUT

      - name: Push Pack to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          allowUpdates: true
          prerelease: true
          name: 模組翻譯包 (git ${{ steps.version.outputs.sha_short }})
          body: |
            ## 📝 下載
            下載下方的 Assets 內的 ``ModsTranslationPack.zip``
            並放入遊戲的資源包中載入即可!

            ## ⭐ 更新
            此翻譯包會在新增新內容時自動更新
            只要到這個頁面重新下載 zip 即可!

            > ${{ steps.current_time.outputs.time }}

            ## ✅ Checksum
            ```
            ${{ steps.checksum.outputs.sum-01 }}
            ${{ steps.checksum.outputs.sum-02 }}
            ```
