name: Auto Package

on:
  push:
    branches:
    - main
    paths:
    - assets/**
    - pack.mcmeta
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  Packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0

      - name: Auto Version Change
        id: version
        run: |
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"
          sed -i 's/GitVersion/git '${GITHUB_SHA::7}'/1' pack.mcmeta

      - name: Make TranslateModPack
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: LICENSE
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename Optimized Pack
        run: |
          mv ./pack.zip TranslateModPack.zip

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Make Checksum
        id: checksum
        run: |
          echo "::set-output name=sum::$(sha256sum TranslateModPack.zip)"

      - name: Make Current Time
        id: current_time
        run: |
          echo "::set-output name=time::$(TZ='Asia/Taipei' date +'最後更新：%Y 年 %m 月 %d 日 %H 點 %M 分')"

      - name: Push Pack to Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "TranslateModPack.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          name: 簡單模組翻譯包 (git ${{ steps.version.outputs.sha_short }})
          body: |
            ## 📝 下載
            下載下方的 Assets 內的 ``TranslateModPack.zip``
            並放入遊戲的材質包中載入即可!

            ## ⭐ 更新
            此翻譯包會在新增新內容時自動更新
            只要到這個頁面重新下載 zip 即可!

            > ${{ steps.current_time.outputs.time }}

            ## ✅ Checksum
            ```
            ${{ steps.checksum.outputs.sum }}
            ```

