name: CI | Contributors Update

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  contributor-update:
    name: Contributors Update
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          avatarSize: 100

      - name: Modify htmlTable README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          message: "docs(Readme): 更新貢獻者清單"
          openDelimiter: '<!-- CONTRIBUTORS_CI_START -->'
          closeDelimiter: '<!-- CONTRIBUTORS_CI_END -->'
          body: '${{steps.contributors.outputs.htmlTable}}'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'docs(Readme): 更新貢獻者清單'
          body: |
            此為自動化工作流程所建立的！
            - 貢獻者清單產生
            
            * 由 [create-pull-request][1] 自動產生
            [1]: https://github.com/peter-evans/create-pull-request
