name: CI | Contributors Update

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  contributor-update:
    name: Contributors Update
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          avatarSize: 100

      - name: Update Readme
        run: |
          python .github/scripts/readme_replacer.py
        env:
          FILE_PATH: "README.md"
          START_TAG: "<!-- CONTRIBUTORS_CI_START -->"
          END_TAG: "<!-- CONTRIBUTORS_CI_END -->"
          CONTENT: "${{steps.contributors.outputs.htmlTable}}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: "docs(Readme): 更新貢獻者清單"
          commit-message: "docs(Readme): 更新貢獻者清單"
          branch: docs/contributor-readme
          add-paths: README.md
          body: |
            此為自動化工作流程所建立的！
            - 由 [create-pull-request][1] 自動產生
            
            [1]: https://github.com/peter-evans/create-pull-request
