name: Release Me

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          pull-request-title-pattern: "chore${scope}: 發佈${component} ${version}"
          labels: "自動發佈：待定"
          release-labels: "自動發佈：已發佈"
          changelog-types: '[{"type":"feat","section":"新增翻譯 & 內容","hidden":false},{"type":"fix","section":"修正翻譯 & 專案","hidden":false},{"type":"chore","section":"清理翻譯 & 專案","hidden":false},{"type":"ci","section":"自動化 Action","hidden":false},{"type":"docs","section":"文檔更新","hidden":false}]'

    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
  
  release-it:
    name: Release It
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
          fetch-depth: 0

      - name: Auto Version Change
        id: version
        run: |
          echo "翻譯包發布版本：${{ needs.release-please.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          sed -i 's/6GitVersion/f${{ needs.release-please.outputs.tag_name }}/1' pack.mcmeta

      - name: Override mods
        run: sh .github/scripts/override_mods.sh

      - name: Make ModsTranslationPack (1.19.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/**/zh_tw/*.lang
            assets/immersiveengineering/manual/zh_tw/*.txt
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.19.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.19.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.19.x.zip

      - name: Change pack format to 1.18.x
        run: |
          sed -i 's/9/8/1' pack.mcmeta

      - name: Make ModsTranslationPack (1.18.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/**/zh_tw/*.lang
            assets/immersiveengineering/manual/zh_tw/*.txt
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.18.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.18.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.18.x.zip

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Make Checksum
        run: |
          SUM0=$(sha256sum ModsTranslationPack-1.19.x.zip)
          SUM1=$(sha256sum ModsTranslationPack-1.18.x.zip)
          echo -e "$SUM0\n$SUM1" > checksums.txt

      - name: Make Changelog
        id: changelog
        run: |
          Tags=${{ needs.release-please.outputs.tag_name }}
          CHANGELOG=$(cat << EOF
          $(curl https://api.github.com/repos/xMikux/ModsTranslationPack/releases/tags/$Tags -H "Accept: application/vnd.github+json" | jq -r .body)
          EOF
          )
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload ModsTranslationPacks
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            *.zip
            checksums.txt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Modrinth (1.18.x)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: cF5VXmkW
          modrinth-unfeature-mode: subset
          name: 模組翻譯包 1.18.x ${{ needs.release-please.outputs.tag_name }}
          version: ${{ needs.release-please.outputs.tag_name }}
          changelog: |
            ${{ env.CHANGELOG }}
          loaders: minecraft
          game-versions: |
            1.18
            1.18.1
            1.18.2
          files-primary: ModsTranslationPack-1.18.x.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: Publish to Modrinth (1.19.x)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: cF5VXmkW
          modrinth-unfeature-mode: subset
          name: 模組翻譯包 1.19.x ${{ needs.release-please.outputs.tag_name }}
          version: ${{ needs.release-please.outputs.tag_name }}
          changelog: |
            ${{ env.CHANGELOG }}
          loaders: minecraft
          game-versions: |
            1.19
            1.19.1
            1.19.2
          files-primary: ModsTranslationPack-1.19.x.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
