name: Release Me

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          pull-request-title-pattern: "chore${scope}: 發佈${component} ${version}"
          labels: "自動發佈：待定"
          release-labels: "自動發佈：已發佈"
          changelog-types: '[{"type":"feat","section":"新增翻譯 & 內容","hidden":false},{"type":"fix","section":"修正翻譯 & 專案","hidden":false},{"type":"chore","section":"清理翻譯 & 專案","hidden":false},{"type":"ci","section":"自動化 Action","hidden":false},{"type":"docs","section":"文檔更新","hidden":false}]'

    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
  
  release-it:
    name: Release It
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
          fetch-depth: 0

      - name: Auto Version Change
        id: version
        run: |
          sed -i 's/6GitVersion/f${{ needs.release-please.outputs.tag_name }}/1' pack.mcmeta

      #    echo "Override Create..."
      #    PATH_Create=assets/create/lang
      #    mkdir -p $PATH_Create
      #    wget https://raw.githubusercontent.com/Creators-of-Create/Create/mc1.18/dev/src/main/resources/assets/create/lang/zh_tw.json -P $PATH_Create

      - name: Override mods
        run: |
          echo ">>> 模組翻譯覆蓋 <<<"
          echo ">>> 某些模組的翻譯如果搭配其他翻譯包"
          echo ">>> 所使用會將翻譯好的內容變成未翻譯"
          echo ">>> 此步驟將會把一些已知的模組翻譯覆蓋掉"

          echo "Override ProjectE..."
          PATH_ProjectE=assets/projecte/lang
          mkdir -p $PATH_ProjectE
          mkdir workdir
          cd workdir
          wget $(wget -qO - "https://www.mediafire.com/file/uhtspihpscmrqsb/ProjectE-1.19.2-PE1.0.1B-tw.jar" > /dev/stdout | grep 'id="downloadButton"' | grep -Po '(?<=href=")[^"]*')
          $JAVA_HOME_17_X64/bin/jar xf ProjectE-1.19.2-PE1.0.1B-tw.jar $PATH_ProjectE/zh_tw.json
          cd ..
          cp workdir/$PATH_ProjectE/zh_tw.json $PATH_ProjectE/
          rm -r workdir

          echo "Override BloodMagic..."
          mkdir workdir
          cd workdir
          sudo apt-get update
          sudo apt-get install -y megatools
          echo "Small Info:"
          echo "The original download link is https://mega.nz/file/KR0CQC5Z#MkEdb3M5q9FHLIgY7WLE18T8EqKFMVUd1guryQWdTQc"
          echo "But megatools look like don't know what is this"
          echo "This fix I see from https://github.com/megous/megatools/issues/157#issuecomment-615835778"
          megadl 'https://mega.nz/#!KR0CQC5Z!MkEdb3M5q9FHLIgY7WLE18T8EqKFMVUd1guryQWdTQc'
          unzip 1.18\ BloodMagic-zh_tw-v2.zip
          cd ..
          mv workdir/assets/bloodmagic assets
          rm -r workdir
          echo "Fix error space"
          sed -i 's/	//1' assets/bloodmagic/patchouli_books/guide/zh_tw/entries/altar/soul_network.json

          echo "Override Tinkers' Construct..."
          PATH_TConstruct=assets/tconstruct/lang
          PATH_TConstruct_Books=assets/tconstruct/book
          mkdir -p $PATH_TConstruct
          mkdir workdir
          cd workdir
          wget $(wget -qO - "https://www.mediafire.com/file/snogv3qqn57o8rf/TConstruct-1.18.2-3.5.2.40-tw.jar" > /dev/stdout | grep 'id="downloadButton"' | grep -Po '(?<=href=")[^"]*')
          $JAVA_HOME_17_X64/bin/jar xf TConstruct-1.18.2-3.5.2.40-tw.jar
          cd ..
          cp workdir/$PATH_TConstruct/zh_tw.json $PATH_TConstruct/
          echo ">> Tinkers' Construct Books"
          echo ">> Setup folders..."
          mkdir -p $PATH_TConstruct_Books/tinkers_gadgetry
          mkdir -p $PATH_TConstruct_Books/puny_smelting
          mkdir -p $PATH_TConstruct_Books/mighty_smelting
          mkdir -p $PATH_TConstruct_Books/materials_and_you
          mkdir -p $PATH_TConstruct_Books/fantastic_foundry
          mkdir -p $PATH_TConstruct_Books/encyclopedia
          echo ">> Setup folder done!"
          echo ">> Copy Tinkers' Construct Books"
          cp -r workdir/$PATH_TConstruct_Books/tinkers_gadgetry/zh_tw $PATH_TConstruct_Books/tinkers_gadgetry
          cp -r workdir/$PATH_TConstruct_Books/puny_smelting/zh_tw $PATH_TConstruct_Books/puny_smelting
          cp -r workdir/$PATH_TConstruct_Books/mighty_smelting/zh_tw $PATH_TConstruct_Books/mighty_smelting
          cp -r workdir/$PATH_TConstruct_Books/materials_and_you/zh_tw $PATH_TConstruct_Books/materials_and_you
          cp -r workdir/$PATH_TConstruct_Books/fantastic_foundry/zh_tw $PATH_TConstruct_Books/fantastic_foundry
          cp -r workdir/$PATH_TConstruct_Books/encyclopedia/zh_tw $PATH_TConstruct_Books/encyclopedia
          echo ">> Copy books done!"
          rm -r workdir

          echo "Override The Twilight Forest..."
          PATH_TwilightForest=assets/twilightforest/lang
          mkdir -p $PATH_TwilightForest
          mkdir workdir
          cd workdir
          wget $(wget -qO - "https://www.mediafire.com/file/kl96rxo50e68j93/twilightforest-1.18.2-4.1.1423-universal-tw.jar" > /dev/stdout | grep 'id="downloadButton"' | grep -Po '(?<=href=")[^"]*')
          $JAVA_HOME_17_X64/bin/jar xf twilightforest-1.18.2-4.1.1423-universal-tw.jar $PATH_TwilightForest/zh_tw.json
          cd ..
          cp workdir/$PATH_TwilightForest/zh_tw.json $PATH_TwilightForest/
          rm -r workdir

          echo "Override Productive Bees..."
          PATH_ProductiveBees=assets/productivebees/lang
          mkdir -p $PATH_ProductiveBees
          mkdir workdir
          cd workdir
          wget $(wget -qO - "https://www.mediafire.com/file/raz0dqfohs5jk29/productivebees-1.19.2-0.10.2.0-tw.jar" > /dev/stdout | grep 'id="downloadButton"' | grep -Po '(?<=href=")[^"]*')
          $JAVA_HOME_17_X64/bin/jar xf productivebees-1.19.2-0.10.2.0-tw.jar $PATH_ProductiveBees/zh_tw.json
          cd ..
          cp workdir/$PATH_ProductiveBees/zh_tw.json $PATH_ProductiveBees/
          rm -r workdir

      - name: Make ModsTranslationPack (1.19.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/encyclopedia/zh_tw/language.lang
            assets/tconstruct/book/mighty_smelting/zh_tw/language.lang
            assets/tconstruct/book/fantastic_foundry/zh_tw/language.lang
            assets/tconstruct/book/materials_and_you/zh_tw/language.lang
            assets/tconstruct/book/tinkers_gadgetry/zh_tw/language.lang
            assets/tconstruct/book/puny_smelting/zh_tw/language.lang
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.19.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.19.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.19.x.zip

      - name: Change pack format to 1.18.x
        run: |
          sed -i 's/9/8/1' pack.mcmeta

      - name: Make ModsTranslationPack (1.18.x)
        uses: ComunidadAylas/PackSquash-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          force_include_files: |
            LICENSE
            assets/tconstruct/book/encyclopedia/zh_tw/language.lang
            assets/tconstruct/book/mighty_smelting/zh_tw/language.lang
            assets/tconstruct/book/fantastic_foundry/zh_tw/language.lang
            assets/tconstruct/book/materials_and_you/zh_tw/language.lang
            assets/tconstruct/book/tinkers_gadgetry/zh_tw/language.lang
            assets/tconstruct/book/puny_smelting/zh_tw/language.lang
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact (1.18.x)
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename ModsTranslationPack (1.18.x)
        run: |
          mv ./pack.zip ModsTranslationPack-1.18.x.zip

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Make Checksum
        run: |
          SUM0=$(sha256sum ModsTranslationPack-1.19.x.zip)
          SUM1=$(sha256sum ModsTranslationPack-1.18.x.zip)
          echo -e "$SUM0\n$SUM1" > checksums.txt

      - name: Make Changelog
        id: changelog
        run: |
          Tags=${{ needs.release-please.outputs.tag_name }}
          CHANGELOG=$(cat << EOF
          $(curl https://api.github.com/repos/xMikux/ModsTranslationPack/releases/tags/$Tags -H "Accept: application/vnd.github+json" | jq -r .body)
          EOF
          )
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload ModsTranslationPacks
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            *.zip
            checksums.txt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Modrinth (1.18.x)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: cF5VXmkW
          modrinth-unfeature-mode: subset
          name: 模組翻譯包 1.18.x ${{ needs.release-please.outputs.tag_name }}
          version: ${{ needs.release-please.outputs.tag_name }}
          changelog: |
            ${{ env.CHANGELOG }}
          loaders: minecraft
          game-versions: |
            1.18
            1.18.1
            1.18.2
          files-primary: ModsTranslationPack-1.18.x.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

      - name: Publish to Modrinth (1.19.x)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: cF5VXmkW
          modrinth-unfeature-mode: subset
          name: 模組翻譯包 1.19.x ${{ needs.release-please.outputs.tag_name }}
          version: ${{ needs.release-please.outputs.tag_name }}
          changelog: |
            ${{ env.CHANGELOG }}
          loaders: minecraft
          game-versions: |
            1.19
            1.19.1
            1.19.2
          files-primary: ModsTranslationPack-1.19.x.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
