name: Verify Commit

on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

permissions:
  contents: read
  pull-requests: read

jobs:
  VerifyCommit:
    name: Verify Commit
    runs-on: ubuntu-latest
    if: github.repository == 'xMikux/ModsTranslationPack'

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
      
      - name: Verify Commit
        run: .github/scripts/verify_commit.sh
